//! The end-to-end pipeline: a `.dar` in, a self-contained bindings **crate**
//! out (`Cargo.toml` + `src/lib.rs`).
//!
//! This is what the `dpm-codegen-rust` binary runs, and what a build script
//! should call. For finer control (emit a single module, post-process the IR
//! first), use [`lower_dar`](crate::lower_dar) and
//! [`generate_crate`](crate::generate_crate) directly.

use std::fs;
use std::path::{Path, PathBuf};

use canton_lf::{Dar, DarError, DecodeError, decode_main_package, package_version};

use crate::{CodegenError, SkippedType, generate_crate, lower_dar};

/// The marker written into a generated `Cargo.toml`, and looked for before
/// overwriting one: a file without it was not written by this tool.
const CARGO_TOML_MARKER: &str = "# generated by dpm-codegen-rust — do not edit by hand";

/// The marker in a generated `lib.rs` (the first line of its crate docs), used
/// to recognize this tool's own output before overwriting. Kept in sync with
/// `crate_docs` — the test below fails if the emitted header stops carrying it.
const LIB_RS_MARKER: &str = "Typed Rust bindings generated from a Daml archive";

/// Writing a bindings crate failed.
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum GenerateError {
    /// The `.dar` could not be read.
    #[error("reading {path}")]
    ReadDar {
        /// The DAR that could not be read.
        path: PathBuf,
        /// The underlying container error.
        #[source]
        source: DarError,
    },
    /// The `.dar` could not be decoded.
    #[error("decoding {path}")]
    DecodeDar {
        /// The DAR that could not be decoded.
        path: PathBuf,
        /// The underlying decode error.
        #[source]
        source: DecodeError,
    },
    /// The archive held no Daml-LF packages to generate from.
    #[error("{path} contains no Daml-LF packages — is it a DAR built with `daml build`?")]
    EmptyDar {
        /// The offending archive.
        path: PathBuf,
    },
    /// The requested crate name is not a valid Cargo package name.
    #[error(
        "`{name}` is not a valid Cargo package name (ASCII letters, digits, `-`/`_`; \
         must not start with a digit)"
    )]
    InvalidCrateName {
        /// The rejected name.
        name: String,
    },
    /// The DAR's package version is not usable as a Cargo version.
    ///
    /// It is refused rather than sanitised because the version reaches the
    /// generated `Cargo.toml`, and a DAR is not necessarily something the
    /// caller wrote.
    #[error(
        "the DAR declares the package version `{version}`, which is not a Cargo version \
         (ASCII letters, digits, `.`, `-`, `+`, `_`). Pass an explicit crate version, or \
         rebuild the DAR with a plain version"
    )]
    InvalidCrateVersion {
        /// The rejected version, as the DAR declared it.
        version: String,
    },
    /// An output file exists and was not written by this tool.
    #[error(
        "{path} already exists and was not generated by this tool; \
         choose an empty output directory or force the overwrite"
    )]
    WouldClobber {
        /// The file that would have been overwritten.
        path: PathBuf,
    },
    /// The generated tokens were not valid Rust — a bug in this crate.
    #[error(transparent)]
    Codegen(#[from] CodegenError),
    /// Writing the output crate failed.
    #[error("writing {path}")]
    Write {
        /// The path being written.
        path: PathBuf,
        /// The underlying I/O error.
        #[source]
        source: std::io::Error,
    },
}

/// How the generated crate depends on the `canton-daml` runtime.
#[derive(Debug, Clone)]
#[non_exhaustive]
pub enum Runtime {
    /// A published version requirement (e.g. `0.2`).
    Version(String),
    /// A local path — for a monorepo, or to try bindings before publishing.
    Path(PathBuf),
}

/// What to generate and where. Build with [`Options::new`], then the
/// `with_*` methods.
///
/// ```no_run
/// use canton_codegen::{Options, Runtime};
///
/// let options = Options::new("my-app-0.1.0.dar", "my-app-bindings")
///     .with_crate_name("my-app-bindings")
///     .with_runtime(Runtime::Version("0.2".to_string()));
/// ```
#[derive(Debug, Clone)]
#[non_exhaustive]
pub struct Options {
    dar: PathBuf,
    out: PathBuf,
    crate_name: Option<String>,
    runtime: Runtime,
    force: bool,
}

impl Options {
    /// Generate bindings for `dar` into the crate directory `out` (created if
    /// absent). The crate name defaults to one derived from the DAR file name
    /// and the runtime to the matching published `canton-daml`.
    pub fn new(dar: impl Into<PathBuf>, out: impl Into<PathBuf>) -> Self {
        Self {
            dar: dar.into(),
            out: out.into(),
            crate_name: None,
            runtime: Runtime::Version(DEFAULT_RUNTIME_REQ.to_string()),
            force: false,
        }
    }

    /// Set the generated crate's package name (default: derived from the DAR
    /// file name — see [`default_crate_name`]).
    #[must_use]
    pub fn with_crate_name(mut self, name: impl Into<String>) -> Self {
        self.crate_name = Some(name.into());
        self
    }

    /// Set how the generated crate depends on the `canton-daml` runtime.
    #[must_use]
    pub fn with_runtime(mut self, runtime: Runtime) -> Self {
        self.runtime = runtime;
        self
    }

    /// Overwrite output files even if they were not generated by this tool.
    #[must_use]
    pub fn with_force(mut self, force: bool) -> Self {
        self.force = force;
        self
    }

    /// The crate name that will be used: the explicit one, or the default
    /// derived from the DAR path.
    #[must_use]
    pub fn crate_name(&self) -> String {
        self.crate_name
            .clone()
            .unwrap_or_else(|| default_crate_name(&self.dar))
    }
}

/// The `canton-daml` version requirement written into a generated crate when
/// the caller does not choose one. Kept in lockstep with this crate's own
/// version, since the SDK crates release together.
const DEFAULT_RUNTIME_REQ: &str = concat!(
    env!("CARGO_PKG_VERSION_MAJOR"),
    ".",
    env!("CARGO_PKG_VERSION_MINOR")
);

/// A summary of a successful generation.
#[derive(Debug, Clone)]
#[non_exhaustive]
pub struct Stats {
    /// Packages in the DAR closure that produced modules.
    pub packages: usize,
    /// Generated Rust submodules.
    pub modules: usize,
    /// Generated named items (data types + templates + interfaces).
    pub items: usize,
    /// Size of the generated `lib.rs`, in bytes.
    pub bytes: usize,
    /// Declarations that could not be lowered (best-effort; surface these as
    /// warnings).
    pub skipped: Vec<SkippedType>,
}

/// Decode `opts.dar`, lower its whole closure, and write a bindings crate
/// (`Cargo.toml` + `src/lib.rs`) into the output directory.
///
/// Refuses to overwrite an existing `Cargo.toml` / `src/lib.rs` that this tool
/// did not generate, unless [`Options::with_force`] is set — a wrong output
/// directory must not clobber a hand-written crate.
///
/// # Errors
/// See [`GenerateError`].
pub fn generate(opts: &Options) -> Result<Stats, GenerateError> {
    let crate_name = opts.crate_name();
    validate_crate_name(&crate_name)?;

    let dar = Dar::open(&opts.dar).map_err(|source| GenerateError::ReadDar {
        path: opts.dar.clone(),
        source,
    })?;
    let (krate, skipped) = lower_dar(&dar).map_err(|source| GenerateError::DecodeDar {
        path: opts.dar.clone(),
        source,
    })?;
    if krate.packages.is_empty() {
        return Err(GenerateError::EmptyDar {
            path: opts.dar.clone(),
        });
    }
    let source = generate_crate(&krate)?;

    let modules = krate.packages.iter().map(|p| p.modules.len()).sum();
    let items = krate
        .packages
        .iter()
        .flat_map(|p| &p.modules)
        .map(|m| m.module.data_types.len() + m.module.templates.len() + m.module.interfaces.len())
        .sum();

    let cargo_toml_path = opts.out.join("Cargo.toml");
    let lib_rs_path = opts.out.join("src").join("lib.rs");
    if !opts.force {
        refuse_foreign(&cargo_toml_path, CARGO_TOML_MARKER)?;
        refuse_foreign(&lib_rs_path, LIB_RS_MARKER)?;
    }

    let src_dir = opts.out.join("src");
    fs::create_dir_all(&src_dir).map_err(|source| GenerateError::Write {
        path: src_dir,
        source,
    })?;
    let version = crate_version(&dar);
    validate_crate_version(&version)?;
    let manifest = cargo_toml(opts, &crate_name, &version);
    fs::write(&cargo_toml_path, manifest).map_err(|source| GenerateError::Write {
        path: cargo_toml_path,
        source,
    })?;
    fs::write(&lib_rs_path, &source).map_err(|source| GenerateError::Write {
        path: lib_rs_path,
        source,
    })?;

    Ok(Stats {
        packages: krate.packages.len(),
        modules,
        items,
        bytes: source.len(),
        skipped,
    })
}

/// Error if `path` exists but does not carry `marker` in its first lines —
/// i.e. it is someone's own file, not a previous run's output.
fn refuse_foreign(path: &Path, marker: &str) -> Result<(), GenerateError> {
    match fs::read_to_string(path) {
        Ok(existing) => {
            let head: String = existing.lines().take(5).collect::<Vec<_>>().join("\n");
            if head.contains(marker) {
                Ok(()) // ours from a previous run — safe to regenerate over
            } else {
                Err(GenerateError::WouldClobber {
                    path: path.to_path_buf(),
                })
            }
        }
        Err(_) => Ok(()), // absent (or unreadable, in which case the write errors)
    }
}

/// The generated crate's version: the DAR main package's version (so
/// `splice-amulet 0.1.14` yields a `0.1.14` crate), or `0.0.0` when the
/// package carries none.
fn crate_version(dar: &Dar) -> String {
    decode_main_package(dar)
        .ok()
        .and_then(|(package, _)| package_version(&package).map(str::to_string))
        .unwrap_or_else(|| "0.0.0".to_string())
}

/// The `Cargo.toml` for the generated crate: a publishable manifest depending
/// on the `canton-daml` runtime.
fn cargo_toml(opts: &Options, crate_name: &str, version: &str) -> String {
    let dependency = match &opts.runtime {
        Runtime::Version(requirement) => format!("canton-daml = \"{requirement}\""),
        Runtime::Path(path) => {
            // A relative path would silently re-anchor at the *output* crate;
            // resolve it against the invoking directory instead. Escaped as a
            // TOML basic string (Windows separators, quotes).
            let absolute = std::path::absolute(path).unwrap_or_else(|_| path.clone());
            format!(
                "canton-daml = {{ path = \"{}\" }}",
                toml_escape(&absolute.display().to_string())
            )
        }
    };
    format!(
        "{CARGO_TOML_MARKER}\n\
         [package]\n\
         name = \"{crate_name}\"\n\
         version = \"{version}\"\n\
         edition = \"2021\"\n\
         description = \"Typed Rust bindings generated from a Daml archive (DAR).\"\n\
         # Fill these in before publishing the generated crate.\n\
         # license = \"Apache-2.0\"\n\
         # repository = \"\"\n\
         \n\
         [dependencies]\n{dependency}\n"
    )
}

/// Escape a string for a double-quoted TOML basic string.
fn toml_escape(raw: &str) -> String {
    raw.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Error unless `name` is a valid Cargo package name: non-empty ASCII
/// alphanumerics, `-` or `_`, not starting with a digit.
/// Refuse a package version that cannot go into a `Cargo.toml` verbatim.
///
/// The version comes out of the DAR, and a DAR is not necessarily something the
/// caller wrote — the package id is the hash of whatever payload its author
/// chose, so every integrity guard upstream still passes one that was authored
/// rather than built. Interpolated raw, a version of the form
/// `0.1.0"` + newline + `[dependencies.evil]` + `git = "…` closed the string
/// and opened a table: an arbitrary dependency in a manifest the caller then
/// compiles.
///
/// The name beside it was already validated and the runtime path beside it
/// already escaped, for this reason. This is the third field in the same
/// manifest and the one that was missed.
///
/// The charset admits everything a real version carries — semver, pre-release
/// tags, build metadata — and nothing that can leave a TOML basic string.
fn validate_crate_version(version: &str) -> Result<(), GenerateError> {
    let valid = !version.is_empty()
        && version
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '-' | '+' | '_'));
    if valid {
        Ok(())
    } else {
        Err(GenerateError::InvalidCrateVersion {
            version: version.to_string(),
        })
    }
}

fn validate_crate_name(name: &str) -> Result<(), GenerateError> {
    let valid = !name.is_empty()
        && !name.starts_with(|c: char| c.is_ascii_digit())
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_');
    if valid {
        Ok(())
    } else {
        Err(GenerateError::InvalidCrateName {
            name: name.to_string(),
        })
    }
}

/// Derive a crate name from a DAR path: its file stem with the trailing
/// version dropped, sanitised to a valid Cargo package name
/// (`splice-amulet-0.1.14.dar` → `splice-amulet`).
///
/// The version is left out on purpose: a DAR version bump should not rename the
/// crate a caller depends on (the *crate version* carries it instead).
#[must_use]
pub fn default_crate_name(dar: &Path) -> String {
    let stem = dar
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("bindings");
    let stem = strip_trailing_version(stem);
    let name: String = stem
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' {
                c
            } else {
                '-'
            }
        })
        .collect();
    let name = name.trim_matches('-').to_string();
    // A Cargo package name cannot be empty or start with a digit.
    if name.is_empty() || name.starts_with(|c: char| c.is_ascii_digit()) {
        format!("bindings-{name}").trim_end_matches('-').to_string()
    } else {
        name
    }
}

/// Drop a trailing `-<version>` (dot-separated digits) from a DAR file stem.
fn strip_trailing_version(stem: &str) -> &str {
    match stem.rsplit_once('-') {
        Some((head, tail))
            if !tail.is_empty()
                && tail
                    .split('.')
                    .all(|part| !part.is_empty() && part.bytes().all(|b| b.is_ascii_digit())) =>
        {
            head
        }
        _ => stem,
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    #[test]
    fn default_crate_names_drop_the_dar_version_and_stay_valid() {
        let cases = [
            // A DAR version bump must not rename the crate.
            ("splice-amulet-0.1.14.dar", "splice-amulet"),
            ("splice-amulet-0.1.15.dar", "splice-amulet"),
            ("quickstart-licensing-0.0.1.dar", "quickstart-licensing"),
            ("quickstart licensing.dar", "quickstart-licensing"),
            // Not a version suffix — kept.
            ("my-app-v2.dar", "my-app-v2"),
            // Degenerate: a name that is only a version keeps its digits
            // behind the `bindings-` prefix (a Cargo name cannot lead with one).
            ("0.1.14.dar", "bindings-0-1-14"),
        ];
        for (input, expected) in cases {
            let name = default_crate_name(Path::new(input));
            assert_eq!(name, expected, "for {input}");
            assert!(validate_crate_name(&name).is_ok(), "{name}");
        }
    }

    #[test]
    fn invalid_crate_names_are_rejected_with_a_typed_error() {
        for bad in ["", "1abc", "has space", "naïve"] {
            assert!(matches!(
                validate_crate_name(bad),
                Err(GenerateError::InvalidCrateName { .. })
            ));
        }
        assert!(validate_crate_name("fine-name_2").is_ok());
    }

    #[test]
    fn cargo_toml_is_publishable_and_escapes_windows_paths() {
        let options = Options::new("x.dar", "out")
            .with_runtime(Runtime::Path(PathBuf::from(r"C:\Users\dev\canton-daml")));
        let toml = cargo_toml(&options, "x", "0.0.0");
        // Backslashes must be escaped or the TOML string is invalid.
        assert!(toml.contains(r"C:\\Users\\dev\\canton-daml"), "{toml}");
        assert!(toml.starts_with(CARGO_TOML_MARKER), "{toml}");
        // A description is present, and no `[workspace]` stanza is forced on
        // the caller's layout.
        assert!(toml.contains("description = "), "{toml}");
        assert!(!toml.contains("[workspace]"), "{toml}");
    }

    #[test]
    fn the_default_runtime_requirement_tracks_this_crate() {
        // Lockstep: a generated crate asks for the runtime that matches the
        // codegen that wrote it.
        assert_eq!(
            DEFAULT_RUNTIME_REQ,
            concat!(
                env!("CARGO_PKG_VERSION_MAJOR"),
                ".",
                env!("CARGO_PKG_VERSION_MINOR")
            )
        );
        assert!(matches!(
            Options::new("x.dar", "o").runtime,
            Runtime::Version(_)
        ));
    }

    /// The clobber guard recognises this tool's own output only if the emitted
    /// header actually contains the marker — so assert against a real emission,
    /// not against the constant.
    #[test]
    fn the_lib_rs_marker_matches_what_the_generator_emits() {
        let emitted = crate::generate_crate(&crate::ir::Crate::default()).unwrap();
        assert!(
            emitted.contains(LIB_RS_MARKER),
            "generated header must carry the marker, got:\n{emitted}"
        );
    }

    #[test]
    fn refuses_to_overwrite_a_foreign_file() {
        let dir = std::env::temp_dir().join(format!("codegen-clobber-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let file = dir.join("Cargo.toml");

        std::fs::write(&file, "[package]\nname = \"users-own-crate\"\n").unwrap();
        assert!(matches!(
            refuse_foreign(&file, CARGO_TOML_MARKER),
            Err(GenerateError::WouldClobber { .. })
        ));

        // Our own previous output is fine to regenerate over, as is an absent file.
        std::fs::write(&file, format!("{CARGO_TOML_MARKER}\n[package]\n")).unwrap();
        assert!(refuse_foreign(&file, CARGO_TOML_MARKER).is_ok());
        assert!(refuse_foreign(&dir.join("absent.toml"), CARGO_TOML_MARKER).is_ok());

        std::fs::remove_dir_all(&dir).ok();
    }
    /// The version reaches `Cargo.toml`, and it comes out of the DAR — which
    /// the caller did not necessarily write. Every integrity guard upstream
    /// still passes an *authored* archive, because the package id is the hash
    /// of whatever payload its author chose.
    ///
    /// Interpolated raw, this closed the string and opened a table: an
    /// arbitrary git dependency in a manifest the caller then compiles. The
    /// name beside it was already validated and the runtime path beside it
    /// already escaped; this was the third field in the same manifest.
    #[test]
    fn a_package_version_cannot_inject_into_the_manifest() {
        let hostile = "0.1.0\"\n[dependencies.evil]\ngit = \"https://example.invalid/repo";
        let error = validate_crate_version(hostile).expect_err("must be refused");
        assert!(
            matches!(error, GenerateError::InvalidCrateVersion { .. }),
            "{error}"
        );
        // The message shows what was rejected, so the reader can go and look at
        // the DAR rather than guess.
        assert!(error.to_string().contains("0.1.0"), "{error}");

        // Neither can a newline on its own, which is all it takes to start a
        // new key once the quote is out.
        assert!(validate_crate_version("0.1.0\nx = 1").is_err());
        assert!(validate_crate_version("").is_err());

        // Everything a real package carries still passes.
        for good in [
            "0.0.0",
            "1.2.3",
            "0.1.14",
            "1.0.0-SNAPSHOT",
            "1.0.0-rc.1+build.5",
            "2.0",
        ] {
            assert!(
                validate_crate_version(good).is_ok(),
                "{good} should be accepted"
            );
        }
    }
}
