//! Core of the `dpm-codegen-rust` CLI: decode a DAR and its dependency closure,
//! lower it, and write a self-contained Rust crate of typed bindings.
//!
//! Kept as a library (with a thin `main.rs` over it) so the generation is
//! testable without spawning the binary.

use std::fs;
use std::path::{Path, PathBuf};

use canton_codegen::{generate_crate, lower_dar};
use canton_lf::{Dar, decode_main_package, package_version};

/// The marker `generate` writes into `Cargo.toml`, and looks for before
/// overwriting one: a file without it was not written by this tool.
const CARGO_TOML_MARKER: &str = "# generated by dpm-codegen-rust — do not edit by hand";

/// The marker `canton-codegen` puts in a generated `lib.rs` (its crate-doc
/// preamble). Used to recognize our own output before overwriting.
const LIB_RS_MARKER: &str = "Generated Daml bindings";

/// How the generated crate depends on the `canton-daml` runtime.
#[derive(Debug, Clone)]
pub enum Runtime {
    /// A published version requirement (e.g. `0.1`).
    Version(String),
    /// A local path — useful in a monorepo or for testing before publish.
    Path(PathBuf),
}

/// What to generate and where.
#[derive(Debug, Clone)]
pub struct Options {
    /// The input `.dar`.
    pub dar: PathBuf,
    /// The output crate directory (created if absent).
    pub out: PathBuf,
    /// The generated crate's package name.
    pub crate_name: String,
    /// The runtime dependency to write into the generated `Cargo.toml`.
    pub runtime: Runtime,
    /// Overwrite output files even if they were not generated by this tool.
    pub force: bool,
}

/// A summary of a successful generation.
#[derive(Debug, Clone)]
pub struct Stats {
    /// Packages in the DAR closure that produced modules.
    pub packages: usize,
    /// Generated Rust submodules.
    pub modules: usize,
    /// Generated named items (data types + templates + interfaces).
    pub items: usize,
    /// Size of the generated `lib.rs`, in bytes.
    pub bytes: usize,
    /// Types that could not be lowered (best-effort; surfaced as warnings).
    pub skipped: Vec<String>,
}

/// Decode `opts.dar`, lower its whole closure, and write a crate
/// (`Cargo.toml` + `src/lib.rs`) into `opts.out`.
///
/// Refuses to overwrite an existing `Cargo.toml` / `src/lib.rs` that this tool
/// did not generate (no marker), unless `opts.force` is set — a wrong `--out`
/// must not clobber a user's hand-written crate.
///
/// # Errors
/// Returns an error if the DAR cannot be read/decoded or contains no Daml-LF
/// packages, the crate name is not a valid Cargo package name, an output file
/// exists and is not ours, the generated tokens are not valid Rust (a generator
/// bug), or the output cannot be written.
pub fn generate(opts: &Options) -> Result<Stats, Box<dyn std::error::Error>> {
    validate_crate_name(&opts.crate_name)?;

    let dar =
        Dar::open(&opts.dar).map_err(|error| format!("reading {}: {error}", opts.dar.display()))?;
    let (krate, errors) =
        lower_dar(&dar).map_err(|error| format!("decoding {}: {error}", opts.dar.display()))?;
    if krate.packages.is_empty() {
        return Err(format!(
            "{} contains no Daml-LF packages — is it a DAR built with `daml build`?",
            opts.dar.display()
        )
        .into());
    }
    let source = generate_crate(&krate)?;

    let modules = krate.packages.iter().map(|p| p.modules.len()).sum();
    let items = krate
        .packages
        .iter()
        .flat_map(|p| &p.modules)
        .map(|m| m.module.data_types.len() + m.module.templates.len() + m.module.interfaces.len())
        .sum();

    let cargo_toml_path = opts.out.join("Cargo.toml");
    let lib_rs_path = opts.out.join("src").join("lib.rs");
    if !opts.force {
        refuse_foreign(&cargo_toml_path, CARGO_TOML_MARKER)?;
        refuse_foreign(&lib_rs_path, LIB_RS_MARKER)?;
    }

    fs::create_dir_all(opts.out.join("src"))
        .map_err(|error| format!("creating {}: {error}", opts.out.display()))?;
    fs::write(&cargo_toml_path, cargo_toml(opts, &crate_version(&dar)))
        .map_err(|error| format!("writing {}: {error}", cargo_toml_path.display()))?;
    fs::write(&lib_rs_path, &source)
        .map_err(|error| format!("writing {}: {error}", lib_rs_path.display()))?;

    Ok(Stats {
        packages: krate.packages.len(),
        modules,
        items,
        bytes: source.len(),
        skipped: errors.into_iter().map(|error| error.0).collect(),
    })
}

/// Error if `path` exists but does not carry `marker` in its first lines —
/// i.e. it is a user's file, not a previous run's output.
fn refuse_foreign(path: &Path, marker: &str) -> Result<(), Box<dyn std::error::Error>> {
    match fs::read_to_string(path) {
        Ok(existing) => {
            let head: String = existing.lines().take(5).collect::<Vec<_>>().join("\n");
            if head.contains(marker) {
                Ok(()) // ours from a previous run — safe to regenerate over
            } else {
                Err(format!(
                    "{} already exists and was not generated by this tool; \
                     choose an empty --out or pass --force to overwrite",
                    path.display()
                )
                .into())
            }
        }
        Err(_) => Ok(()), // absent (or unreadable, in which case the write errors)
    }
}

/// The generated crate's version: the DAR main package's version (so
/// `splice-amulet 0.1.14` yields a `0.1.14` crate), or `0.0.0` when the
/// package carries none.
fn crate_version(dar: &Dar) -> String {
    decode_main_package(dar)
        .ok()
        .and_then(|(package, _)| package_version(&package).map(str::to_string))
        .unwrap_or_else(|| "0.0.0".to_string())
}

/// The `Cargo.toml` for the generated crate: a standalone (`[workspace]`) crate
/// depending on the `canton-daml` runtime.
fn cargo_toml(opts: &Options, version: &str) -> String {
    let dependency = match &opts.runtime {
        Runtime::Version(version) => format!("canton-daml = \"{version}\""),
        Runtime::Path(path) => {
            // A relative path would silently re-anchor at the *output* crate;
            // resolve it against the invoking directory instead. Escaped as a
            // TOML basic string (Windows separators, quotes).
            let absolute = std::path::absolute(path).unwrap_or_else(|_| path.clone());
            format!(
                "canton-daml = {{ path = \"{}\" }}",
                toml_escape(&absolute.display().to_string())
            )
        }
    };
    format!(
        "{CARGO_TOML_MARKER}\n\
         [package]\nname = \"{name}\"\nversion = \"{version}\"\nedition = \"2021\"\n\n\
         [dependencies]\n{dependency}\n\n\
         # Generated bindings are their own crate; depend on it by path.\n\
         [workspace]\n",
        name = opts.crate_name,
    )
}

/// Escape a string for a double-quoted TOML basic string.
fn toml_escape(raw: &str) -> String {
    raw.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Error unless `name` is a valid Cargo package name: non-empty ASCII
/// alphanumerics, `-` or `_`, not starting with a digit.
fn validate_crate_name(name: &str) -> Result<(), Box<dyn std::error::Error>> {
    let valid = !name.is_empty()
        && !name.starts_with(|c: char| c.is_ascii_digit())
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_');
    if valid {
        Ok(())
    } else {
        Err(format!(
            "`{name}` is not a valid Cargo package name \
             (ASCII letters, digits, `-`/`_`; must not start with a digit) — pass --name"
        )
        .into())
    }
}

/// Derive a crate name from a DAR path: its file stem, sanitised to a valid
/// Cargo package name (`splice-amulet-0.1.14.dar` → `splice-amulet-0-1-14`).
#[must_use]
pub fn default_crate_name(dar: &std::path::Path) -> String {
    let stem = dar
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("bindings");
    let name: String = stem
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' {
                c
            } else {
                '-'
            }
        })
        .collect();
    // A Cargo package name cannot be empty or start with a digit.
    if name.is_empty() || name.starts_with(|c: char| c.is_ascii_digit()) {
        format!("bindings-{}", name.trim_start_matches('-'))
            .trim_end_matches('-')
            .to_string()
    } else {
        name
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    #[test]
    fn default_crate_names_are_valid_cargo_names() {
        let cases = [
            ("splice-amulet-0.1.14.dar", "splice-amulet-0-1-14"),
            ("quickstart licensing.dar", "quickstart-licensing"),
            // A leading digit is not a valid Cargo package name.
            ("0.1.14.dar", "bindings-0-1-14"),
        ];
        for (input, expected) in cases {
            let name = default_crate_name(Path::new(input));
            assert_eq!(name, expected);
            assert!(validate_crate_name(&name).is_ok(), "{name}");
        }
    }

    #[test]
    fn invalid_crate_names_are_rejected_with_guidance() {
        for bad in ["", "1abc", "has space", "naïve"] {
            let error = validate_crate_name(bad).unwrap_err().to_string();
            assert!(error.contains("--name"), "{error}");
        }
        assert!(validate_crate_name("fine-name_2").is_ok());
    }

    #[test]
    fn cargo_toml_escapes_windows_style_paths() {
        let opts = Options {
            dar: PathBuf::from("x.dar"),
            out: PathBuf::from("out"),
            crate_name: "x".to_string(),
            runtime: Runtime::Path(PathBuf::from(r"C:\Users\dev\canton-daml")),
            force: false,
        };
        let toml = cargo_toml(&opts, "0.0.0");
        // Backslashes must be escaped or the TOML string is invalid.
        assert!(toml.contains(r"C:\\Users\\dev\\canton-daml"), "{toml}");
        assert!(toml.starts_with(CARGO_TOML_MARKER), "{toml}");
    }

    #[test]
    fn refuses_to_overwrite_a_foreign_file_without_force() {
        let dir = std::env::temp_dir().join(format!("codegen-clobber-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let user_file = dir.join("Cargo.toml");
        std::fs::write(&user_file, "[package]\nname = \"users-own-crate\"\n").unwrap();

        let error = refuse_foreign(&user_file, CARGO_TOML_MARKER)
            .unwrap_err()
            .to_string();
        assert!(error.contains("--force"), "{error}");

        // Our own previous output (marker present) is fine to overwrite.
        std::fs::write(&user_file, format!("{CARGO_TOML_MARKER}\n[package]\n")).unwrap();
        assert!(refuse_foreign(&user_file, CARGO_TOML_MARKER).is_ok());

        // Absent file is fine.
        assert!(refuse_foreign(&dir.join("absent.toml"), CARGO_TOML_MARKER).is_ok());
        std::fs::remove_dir_all(&dir).ok();
    }
}
