//! `dpm-codegen-rust` — generate a typed Rust crate from a DAR.
//!
//! Invoked as `dpm codegen-rust` (dpm resolves subcommands to `dpm-<name>`
//! binaries, like git/cargo) or standalone. Designed to be called from a build
//! script the way `prost-build` is, so a change to a DAR regenerates bindings.

use std::path::PathBuf;
use std::process::ExitCode;

use canton_codegen_cli::{Options, Runtime, default_crate_name, generate};

const USAGE: &str = "\
dpm-codegen-rust — generate a typed Rust crate from a DAR

USAGE:
    dpm-codegen-rust --dar <PATH> --out <DIR> [OPTIONS]

OPTIONS:
    --dar <PATH>              Input .dar (with its dependency closure)
    --out <DIR>               Output crate directory (created if absent)
    --name <NAME>             Generated crate name [default: derived from the DAR]
    --runtime-path <PATH>     Depend on canton-daml by path (default: by version)
    --runtime-version <VER>   canton-daml version requirement [default: 0.1]
    --force                   Overwrite output files not generated by this tool
    -h, --help                Print this help
    -V, --version             Print the version
";

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("error: {error}");
            ExitCode::FAILURE
        }
    }
}

fn run() -> Result<(), Box<dyn std::error::Error>> {
    let mut dar: Option<PathBuf> = None;
    let mut out: Option<PathBuf> = None;
    let mut name: Option<String> = None;
    let mut runtime_path: Option<PathBuf> = None;
    let mut runtime_version: Option<String> = None;
    let mut force = false;

    let mut args = std::env::args().skip(1);
    while let Some(arg) = args.next() {
        // Accept both `--flag value` and `--flag=value`.
        let (flag, mut inline) = match arg.split_once('=') {
            Some((flag, value)) => (flag.to_string(), Some(value.to_string())),
            None => (arg, None),
        };
        let mut value = |args: &mut dyn Iterator<Item = String>,
                         flag: &str|
         -> Result<String, Box<dyn std::error::Error>> {
            match inline.take() {
                Some(inline) => Ok(inline),
                None => args
                    .next()
                    .ok_or_else(|| format!("{flag} needs a value\n\n{USAGE}").into()),
            }
        };
        match flag.as_str() {
            "-h" | "--help" => {
                print!("{USAGE}");
                return Ok(());
            }
            "-V" | "--version" => {
                println!("dpm-codegen-rust {}", env!("CARGO_PKG_VERSION"));
                return Ok(());
            }
            "--force" => force = true,
            "--dar" => dar = Some(PathBuf::from(value(&mut args, "--dar")?)),
            "--out" => out = Some(PathBuf::from(value(&mut args, "--out")?)),
            "--name" => name = Some(value(&mut args, "--name")?),
            "--runtime-path" => {
                runtime_path = Some(PathBuf::from(value(&mut args, "--runtime-path")?));
            }
            "--runtime-version" => {
                runtime_version = Some(value(&mut args, "--runtime-version")?);
            }
            other => return Err(format!("unexpected argument `{other}`\n\n{USAGE}").into()),
        }
    }

    let dar = dar.ok_or(format!("missing required --dar\n\n{USAGE}"))?;
    let out = out.ok_or(format!("missing required --out\n\n{USAGE}"))?;
    let crate_name = name.unwrap_or_else(|| default_crate_name(&dar));
    let version_dependency = runtime_path.is_none();
    let runtime = match runtime_path {
        Some(path) => Runtime::Path(path),
        None => Runtime::Version(runtime_version.unwrap_or_else(|| "0.1".to_string())),
    };

    let stats = generate(&Options {
        dar,
        out: out.clone(),
        crate_name: crate_name.clone(),
        runtime,
        force,
    })?;

    eprintln!(
        "generated `{crate_name}` in {}: {} packages / {} modules / {} items / {} KB",
        out.display(),
        stats.packages,
        stats.modules,
        stats.items,
        stats.bytes / 1024,
    );
    if version_dependency {
        eprintln!(
            "note: the crate depends on `canton-daml` from crates.io; \
             if it fails to resolve, re-run with --runtime-path <checkout>/crates/canton-daml"
        );
    }
    if !stats.skipped.is_empty() {
        eprintln!(
            "warning: {} type(s) could not be lowered and were skipped:",
            stats.skipped.len()
        );
        for message in stats.skipped.iter().take(20) {
            eprintln!("  - {message}");
        }
        if stats.skipped.len() > 20 {
            eprintln!("  … and {} more", stats.skipped.len() - 20);
        }
    }
    Ok(())
}
