//! `dpm-codegen-rust` — generate a typed Rust crate from a DAR.
//!
//! Invoked as `dpm codegen-rust` (dpm resolves subcommands to `dpm-<name>`
//! binaries, like git/cargo) or standalone. The pipeline itself lives in the
//! `canton-codegen` library, so a build script can call it directly the way
//! `prost-build` is used, without depending on this CLI.

use std::path::PathBuf;
use std::process::ExitCode;

use canton_codegen::{GenerateError, Options, Runtime, generate};

const USAGE: &str = "\
dpm-codegen-rust — generate a typed Rust crate from a DAR

USAGE:
    dpm-codegen-rust --dar <PATH> --out <DIR> [OPTIONS]

OPTIONS:
    --dar <PATH>              Input .dar (with its dependency closure)
    --out <DIR>               Output crate directory (created if absent)
    --name <NAME>             Generated crate name [default: derived from the DAR]
    --runtime-path <PATH>     Depend on canton-daml by path (default: by version)
    --runtime-version <VER>   canton-daml version requirement [default: matches this tool]
    --force                   Overwrite output files not generated by this tool
    -h, --help                Print this help
    -V, --version             Print the version
";

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            // Print the whole cause chain: the top-level message names the
            // operation, the source names the underlying failure.
            eprint!("error: {error}");
            let mut cause = std::error::Error::source(&*error);
            while let Some(error) = cause {
                eprint!(": {error}");
                cause = error.source();
            }
            eprintln!();
            ExitCode::FAILURE
        }
    }
}

/// A CLI-level failure: bad arguments, or a generation error.
#[derive(Debug, thiserror::Error)]
enum CliError {
    #[error("{0}\n\n{USAGE}")]
    Usage(String),
    #[error(transparent)]
    Generate(#[from] GenerateError),
}

fn run() -> Result<(), Box<CliError>> {
    let mut dar: Option<PathBuf> = None;
    let mut out: Option<PathBuf> = None;
    let mut name: Option<String> = None;
    let mut runtime_path: Option<PathBuf> = None;
    let mut runtime_version: Option<String> = None;
    let mut force = false;

    let usage = |message: String| Box::new(CliError::Usage(message));

    let mut args = std::env::args().skip(1);
    while let Some(arg) = args.next() {
        // Accept both `--flag value` and `--flag=value`.
        let (flag, mut inline) = match arg.split_once('=') {
            Some((flag, value)) => (flag.to_string(), Some(value.to_string())),
            None => (arg, None),
        };
        let mut value = |args: &mut dyn Iterator<Item = String>, flag: &str| match inline.take() {
            Some(inline) => Ok(inline),
            None => args
                .next()
                .ok_or_else(|| usage(format!("{flag} needs a value"))),
        };
        match flag.as_str() {
            "-h" | "--help" | "-V" | "--version" => {
                if let Some(value) = inline.take() {
                    return Err(usage(format!("{flag} takes no value (got `={value}`)")));
                }
                if flag == "-h" || flag == "--help" {
                    print!("{USAGE}");
                } else {
                    println!("dpm-codegen-rust {}", env!("CARGO_PKG_VERSION"));
                }
                return Ok(());
            }
            // A boolean flag takes no value: `--force=false` must not be read
            // as "enable force" (it would destroy the caller's files).
            "--force" => {
                if let Some(value) = inline.take() {
                    return Err(usage(format!(
                        "--force is a flag and takes no value (got `={value}`)"
                    )));
                }
                force = true;
            }
            "--dar" => dar = Some(PathBuf::from(value(&mut args, "--dar")?)),
            "--out" => out = Some(PathBuf::from(value(&mut args, "--out")?)),
            "--name" => name = Some(value(&mut args, "--name")?),
            "--runtime-path" => {
                runtime_path = Some(PathBuf::from(value(&mut args, "--runtime-path")?));
            }
            "--runtime-version" => {
                runtime_version = Some(value(&mut args, "--runtime-version")?);
            }
            other => return Err(usage(format!("unexpected argument `{other}`"))),
        }
    }

    let dar = dar.ok_or_else(|| usage("missing required --dar".to_string()))?;
    let out = out.ok_or_else(|| usage("missing required --out".to_string()))?;

    let mut options = Options::new(dar, out.clone()).with_force(force);
    if let Some(name) = name {
        options = options.with_crate_name(name);
    }
    let by_version = runtime_path.is_none();
    if let Some(path) = runtime_path {
        options = options.with_runtime(Runtime::Path(path));
    } else if let Some(requirement) = runtime_version {
        options = options.with_runtime(Runtime::Version(requirement));
    }
    let crate_name = options.crate_name();

    let stats = generate(&options)
        .map_err(CliError::from)
        .map_err(Box::new)?;

    eprintln!(
        "generated `{crate_name}` in {}: {} packages / {} modules / {} items / {} KB",
        out.display(),
        stats.packages,
        stats.modules,
        stats.items,
        stats.bytes / 1024,
    );
    if by_version {
        eprintln!(
            "note: the crate depends on `canton-daml` from crates.io; \
             if it fails to resolve, re-run with --runtime-path <checkout>/crates/canton-daml"
        );
    }
    if !stats.skipped.is_empty() {
        eprintln!(
            "warning: {} declaration(s) could not be lowered and were skipped:",
            stats.skipped.len()
        );
        for skipped in stats.skipped.iter().take(20) {
            eprintln!("  - {skipped}");
        }
        if stats.skipped.len() > 20 {
            eprintln!("  … and {} more", stats.skipped.len() - 20);
        }
    }
    Ok(())
}
