//! Always-on pipeline tests over the checked-in fixture DAR
//! (`testdata/splice-api-token-holding-v1-1.0.0.dar`) — the one coverage the
//! env-gated suites cannot give CI: every `cargo test` runs the real
//! decode → lower → emit path on a real DAR, with no external setup.
//!
//! (Template/choice/key *emission* is separately always-on: the committed
//! `canton-splice-*` binding crates are workspace members, so CI compiles
//! their generated templates on every push.)

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::path::{Path, PathBuf};

use canton_codegen::{GenerateError, Options, Runtime, generate};
use canton_codegen::{generate_crate, lower_dar};
use canton_lf::Dar;

fn fixture() -> PathBuf {
    PathBuf::from(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../testdata/splice-api-token-holding-v1-1.0.0.dar"
    ))
}

/// A scratch directory unique to this test, cleaned before use.
fn scratch(name: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("codegen-fixture-{name}-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    dir
}

#[test]
fn fixture_dar_lowers_and_generates_valid_rust() {
    let dar = Dar::open(fixture()).expect("open the fixture DAR");
    let (krate, errors) = lower_dar(&dar).expect("decode + lower");

    // Nothing user-facing may be skipped. The one benign class is GHC-internal
    // compiler artifacts in daml-prim whose names are not Rust identifiers
    // (e.g. `GHC.Prim: Void$u0023` — `$u0023` is an escaped `#`); before the
    // identifier guard those panicked the emitter, now they skip with context.
    let unexpected: Vec<_> = errors
        .iter()
        .filter(|error| {
            !(error.module().starts_with("GHC.")
                && error
                    .reason()
                    .contains("not representable as a Rust identifier"))
        })
        .collect();
    assert!(
        unexpected.is_empty(),
        "only GHC-internal identifier skips are expected: {unexpected:?}"
    );
    assert!(krate.packages.len() >= 20, "the closure lowers fully");

    let source = generate_crate(&krate).expect("emit");
    syn::parse_file(&source).expect("generated source parses as Rust");

    // Golden spot-checks: the Holding interface surface is present.
    assert!(
        source.contains("impl rt::Interface for Holding"),
        "interface impl"
    );
    assert!(source.contains("HoldingView"), "interface view type");
    assert!(source.contains("impl rt::Choice<"), "interface choices");
    // The SCU-friendly identity is wired through (the Daml package name that
    // backs the `#<package-name>` template-id form).
    assert!(
        source.contains("const PACKAGE_NAME: &'static str = \"splice-api-token-holding-v1\""),
        "package name for the #name template-id form"
    );
}

#[test]
fn generation_is_deterministic() {
    let dar = Dar::open(fixture()).expect("open the fixture DAR");
    let generate_once = || {
        let (krate, _) = lower_dar(&dar).expect("lower");
        generate_crate(&krate).expect("emit")
    };
    assert_eq!(
        generate_once(),
        generate_once(),
        "two generations from one DAR must be byte-identical"
    );
}

#[test]
fn cli_generate_writes_a_versioned_marked_crate_and_respects_clobber_rules() {
    let out = scratch("cli");
    let opts = Options::new(fixture(), out.clone())
        .with_crate_name("holding-bindings")
        .with_runtime(Runtime::Path(PathBuf::from(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../canton-daml"
        ))));

    let stats = generate(&opts).expect("generation succeeds");
    assert!(stats.packages >= 20 && stats.items > 0);

    let cargo_toml = std::fs::read_to_string(out.join("Cargo.toml")).unwrap();
    assert!(
        cargo_toml.starts_with("# generated by dpm-codegen-rust"),
        "marker first: {cargo_toml}"
    );
    // The crate version is the DAR's package version, not a placeholder.
    assert!(cargo_toml.contains("version = \"1.0.0\""), "{cargo_toml}");
    let lib_rs = std::fs::read_to_string(out.join("src/lib.rs")).unwrap();
    assert!(lib_rs.contains("Generated Daml bindings"), "lib.rs marker");

    // Re-running over our own output is fine (regeneration)…
    generate(&opts).expect("regenerating over own output succeeds");
    // …but a foreign file is refused without --force.
    std::fs::write(out.join("src/lib.rs"), "fn user_wrote_this() {}").unwrap();
    let error = generate(&opts).unwrap_err();
    assert!(
        matches!(&error, GenerateError::WouldClobber { path } if path.ends_with("lib.rs")),
        "expected WouldClobber, got {error:?}"
    );
    generate(&opts.clone().with_force(true)).expect("force overwrites");

    std::fs::remove_dir_all(&out).ok();
}

#[test]
fn cli_rejects_a_non_dar_input_with_a_clear_error() {
    let out = scratch("nondar");
    let not_a_dar = out.join("fake.dar");
    std::fs::create_dir_all(&out).unwrap();
    std::fs::write(&not_a_dar, "plain text, not a zip").unwrap();

    let error =
        generate(&Options::new(not_a_dar.clone(), out.join("bindings")).with_crate_name("x"))
            .unwrap_err();
    // A typed variant naming the offending path — callers can match on this
    // instead of scraping the message.
    let GenerateError::ReadDar { path, source } = &error else {
        panic!("expected ReadDar, got {error:?}");
    };
    assert_eq!(path, &not_a_dar);
    // …and the cause says what was expected.
    assert!(source.to_string().contains("daml build"), "{source}");
    assert!(Path::new(&not_a_dar).exists());

    std::fs::remove_dir_all(&out).ok();
}
