//! Tests that run the actual `dpm-codegen-rust` binary — argument parsing,
//! exit codes, and the guarantees a user relies on at the command line.
//!
//! The generation pipeline itself is tested in `canton-codegen`; what is
//! covered here is only reachable by executing the binary.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::path::{Path, PathBuf};
use std::process::{Command, Output};

/// The DAR fixture, and a scratch directory unique to each test.
fn fixture() -> PathBuf {
    PathBuf::from(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../testdata/splice-api-token-holding-v1-1.0.0.dar"
    ))
}

fn scratch(name: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("dpm-codegen-cli-{name}-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    dir
}

fn run(args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_dpm-codegen-rust"))
        .args(args)
        .output()
        .expect("run the binary")
}

fn stderr(output: &Output) -> String {
    String::from_utf8_lossy(&output.stderr).into_owned()
}

/// A directory holding a file the user wrote, which the tool must not destroy.
fn with_user_file(dir: &Path) -> PathBuf {
    let lib = dir.join("src/lib.rs");
    std::fs::create_dir_all(dir.join("src")).unwrap();
    std::fs::write(&lib, "fn user_wrote_this() {}").unwrap();
    std::fs::write(dir.join("Cargo.toml"), "[package]\nname = \"mine\"\n").unwrap();
    lib
}

#[test]
fn boolean_flags_reject_an_inline_value() {
    // Regression: `--force=false` was parsed as "enable --force", so a user
    // trying to *disable* it had their files overwritten instead.
    let dir = scratch("force-eq");
    let user_file = with_user_file(&dir);

    let dar = fixture();
    let output = run(&[
        "--dar",
        dar.to_str().unwrap(),
        "--out",
        dir.to_str().unwrap(),
        "--force=false",
    ]);

    assert!(!output.status.success(), "must fail, not silently force");
    assert!(
        stderr(&output).contains("takes no value"),
        "{}",
        stderr(&output)
    );
    assert_eq!(
        std::fs::read_to_string(&user_file).unwrap(),
        "fn user_wrote_this() {}",
        "the user's file must be untouched"
    );
    std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn refuses_to_clobber_a_foreign_crate_then_obeys_force() {
    let dir = scratch("clobber");
    let user_file = with_user_file(&dir);
    let dar = fixture();
    let args = [
        "--dar",
        dar.to_str().unwrap(),
        "--out",
        dir.to_str().unwrap(),
        "--runtime-path",
        concat!(env!("CARGO_MANIFEST_DIR"), "/../canton-daml"),
    ];

    let refused = run(&args);
    assert!(!refused.status.success());
    assert!(
        stderr(&refused).contains("not generated by this tool"),
        "{}",
        stderr(&refused)
    );
    assert_eq!(
        std::fs::read_to_string(&user_file).unwrap(),
        "fn user_wrote_this() {}"
    );

    // With --force the same invocation proceeds.
    let mut forced: Vec<&str> = args.to_vec();
    forced.push("--force");
    let output = run(&forced);
    assert!(output.status.success(), "{}", stderr(&output));
    assert!(
        std::fs::read_to_string(&user_file)
            .unwrap()
            .contains("Typed Rust bindings generated from a Daml archive")
    );
    std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn generates_and_is_idempotent() {
    let dir = scratch("generate");
    let dar = fixture();
    let args = [
        "--dar",
        dar.to_str().unwrap(),
        "--out",
        dir.to_str().unwrap(),
        "--runtime-path",
        concat!(env!("CARGO_MANIFEST_DIR"), "/../canton-daml"),
    ];

    let first = run(&args);
    assert!(first.status.success(), "{}", stderr(&first));
    assert!(stderr(&first).contains("generated"), "{}", stderr(&first));
    let source = std::fs::read_to_string(dir.join("src/lib.rs")).unwrap();

    // Re-running over the tool's own output needs no --force and is stable.
    let second = run(&args);
    assert!(second.status.success(), "{}", stderr(&second));
    assert_eq!(
        source,
        std::fs::read_to_string(dir.join("src/lib.rs")).unwrap()
    );
    std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn usage_errors_are_actionable_and_exit_nonzero() {
    // Missing arguments, unknown flags, and a flag with no value all print the
    // usage text rather than a bare message.
    for args in [
        vec!["--dar", "x.dar"], // missing --out
        vec!["--out", "x"],     // missing --dar
        vec!["--nonsense"],     // unknown flag
        vec!["--dar"],          // flag with no value
    ] {
        let output = run(&args);
        assert!(!output.status.success(), "{args:?} should fail");
        let message = stderr(&output);
        assert!(message.contains("USAGE:"), "{args:?}: {message}");
    }
}

#[test]
fn two_ways_of_naming_the_runtime_dependency_is_a_usage_error() {
    // Both flags answer the same question. Honouring the path and dropping the
    // version — the same silent swallow of an explicit intent that `--force=false`
    // was — writes a manifest the user did not ask for, with nothing to notice.
    let dir = scratch("runtime-conflict");
    let output = run(&[
        "--dar",
        fixture().to_str().unwrap(),
        "--out",
        dir.join("out").to_str().unwrap(),
        "--runtime-path",
        "/somewhere/canton-daml",
        "--runtime-version",
        "0.2",
    ]);
    assert!(!output.status.success(), "should be rejected");
    let message = stderr(&output);
    assert!(message.contains("--runtime-path"), "{message}");
    assert!(message.contains("--runtime-version"), "{message}");
    assert!(
        !dir.join("out").exists(),
        "nothing should be written when the arguments are rejected"
    );
}

#[test]
fn help_and_version_succeed() {
    let help = run(&["--help"]);
    assert!(help.status.success());
    assert!(String::from_utf8_lossy(&help.stdout).contains("--runtime-path"));

    let version = run(&["-V"]);
    assert!(version.status.success());
    assert!(
        String::from_utf8_lossy(&version.stdout).contains(env!("CARGO_PKG_VERSION")),
        "version output should name the crate version"
    );
}

#[test]
fn a_non_dar_input_fails_with_the_path_and_a_hint() {
    let dir = scratch("nondar");
    let fake = dir.join("fake.dar");
    std::fs::write(&fake, "not a zip").unwrap();

    let output = run(&[
        "--dar",
        fake.to_str().unwrap(),
        "--out",
        dir.join("out").to_str().unwrap(),
    ]);
    assert!(!output.status.success());
    let message = stderr(&output);
    // The whole cause chain is printed: what we were doing, and why it failed.
    assert!(message.contains("fake.dar"), "{message}");
    assert!(message.contains("daml build"), "{message}");
    std::fs::remove_dir_all(&dir).ok();
}
